[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  publish = "web"
  port = 3000

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@shopify"]
