# Version of the configuration
api_version = "2024-01"

# Type of the extension
extension_points = [
  "ThemeAppExtension"
]

# Human-readable name of the extension
name = "Custom Engraving"

type = "theme_app_extension"

# Extension settings
[settings.definition]
name = "Engraving Settings"
target = "apps"

[[settings.definitions]]
name = "engraving_enabled"
type = "boolean"
label = "Enable Engraving"
help_text = "Enable or disable the engraving feature"

[[settings.definitions]]
name = "engraving_price"
type = "number"
label = "Engraving Price"
help_text = "Additional price for engraving"
validations = [
  { name = "min", value = 0 },
  { name = "max", value = 1000 }
]

[[settings.definitions]]
name = "engraving_label"
type = "string"
label = "Engraving Label"
help_text = "Label for the engraving option"
default = "Add Custom Engraving"

# The extension's entry point
[[extension_points]]
target = "theme.cart-drawer.drawer"
module = "./dist/extension.js"

[[extension_points]]
target = "theme.main-product"
module = "./dist/extension.js"
]

# Capabilities the extension needs (optional)
capabilities = {
  network_access = false,
  block_progress = false,
  api_access = true,
}

# Extension settings (optional)
[settings]
  [settings.fields]
  [settings.fields.engraving_price]
  name = "engraving_price"
  description = "Price to charge for engraving (in USD)"
  type = "number"
  required = true
  default = 10.00

  [settings.fields.max_characters]
  name = "max_characters"
  description = "Maximum number of characters allowed for engraving"
  type = "number"
  required = true
  default = 50

  [settings.fields.enabled]
  name = "enabled"
  description = "Enable custom engraving"
  type = "boolean"
  required = true
  default = true
